// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MvcMovie.Models;
using System;

namespace MvcMovie.Migrations
{
  [DbContext(typeof(MvcMovieContext))]
  [Migration("20180226185052_director")]
  partial class director
  {
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
          .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

      modelBuilder.Entity("MvcMovie.Models.Director", b =>
      {
        b.Property<int>("Id")
          .ValueGeneratedOnAdd();

        b.Property<string>("Name");

        b.HasKey("Id");

        b.ToTable("Director");
      });

      modelBuilder.Entity("MvcMovie.Models.Movie", b =>
          {
            b.Property<int>("ID")
                      .ValueGeneratedOnAdd();

            b.Property<string>("Genre");

            b.Property<decimal>("Price");

            b.Property<DateTime>("ReleaseDate");

            b.Property<string>("Title");

            b.HasKey("ID");

            b.ToTable("Movie");
          });
#pragma warning restore 612, 618
    }
  }
}
